# Generated by Django 3.2.5 on 2021-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_remove_notes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
