# Generated by Django 3.2.5 on 2021-07-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
